{
 "title": "User-Service Performance",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Общий RPS по сервису",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "RPS по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (uri, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий Error Rate по сервису (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{status=~\"5.*\"}[1m])) / sum(rate(http_server_requests_seconds_count[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate по эндпоинтам (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(http_server_requests_seconds_count{status=~\"5.*\"}[1m])) by (uri, method)\r\n  /\r\n    sum(rate(http_server_requests_seconds_count[1m])) by (uri, method)\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency по эндпоинтам (0.5 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, uri, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency по эндпоинтам (0.95 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, uri, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency по эндпоинтам (0.99 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, uri, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency по эндпоинтам (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max) by (uri, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий Latency Ingress (0.5 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий Latency Ingress (0.95 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий Latency Ingress (0.99 квантиль)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий Latency Ingress (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "max(nginx_ingress_controller_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}