apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: prod
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 2admi/minimal-auth-service:0.0.1
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: "postgres-auth"
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: "auth_service_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
