apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.statefulset.appLabel }}
  serviceName: {{ .Values.statefulset.serviceName | quote }}
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.appLabel }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.passwordKey }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volume.name }}
      spec:
        accessModes: [ {{ .Values.volume.accessMode | quote }} ]
        resources:
          requests:
            storage: {{ .Values.volume.storage }}
