apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.migrationConfig.name }}
  namespace: {{ .Values.deployment.namespace }}
data:
  migration.sql: |
    CREATE SCHEMA IF NOT EXISTS {{ .Values.database.schema }};

    CREATE TABLE IF NOT EXISTS {{ .Values.database.schema }}.{{ .Values.database.tableName }} (
                                                                                                  id SERIAL PRIMARY KEY,
                                                                                                  username VARCHAR(256) NOT NULL,
        first_name VARCHAR(256) NOT NULL,
        last_name VARCHAR(256) NOT NULL,
        email VARCHAR(256) NOT NULL,
        phone VARCHAR(20) NOT NULL,
        CONSTRAINT unique_username UNIQUE (username),
        CONSTRAINT unique_email UNIQUE (email)
        );

    CREATE INDEX IF NOT EXISTS idx_{{ .Values.database.tableName }}_username ON {{ .Values.database.schema }}.{{ .Values.database.tableName }} (username);
    CREATE INDEX IF NOT EXISTS idx_{{ .Values.database.tableName }}_email ON {{ .Values.database.schema }}.{{ .Values.database.tableName }} (email);
