apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.migrationConfig.name }}
  namespace: {{ .Values.deployment.namespace }}
data:
  migration.sql: |
    CREATE SCHEMA IF NOT EXISTS {{ .Values.database.schema }};

    CREATE TABLE IF NOT EXISTS {{ .Values.database.schema }}.{{ .Values.database.tableName }} (
                                                                                                  id BIGINT PRIMARY KEY,
        first_name VARCHAR(256) NOT NULL,
        last_name VARCHAR(256) NOT NULL,
        phone VARCHAR(20) NOT NULL
        );
